import 'package:buildacre_crm/core/constants/app_constants.dart';
import 'package:buildacre_crm/features/leads/models/lead.dart';

final mockLeads = <Lead>[
  // tc_1 — Ravi Kumar
  Lead(
    id: '1',
    name: 'Rajesh Kumar',
    phone: '9876543210',
    email: 'rajesh.k@gmail.com',
    source: LeadSource.facebook,
    serviceType: ServiceType.construction,
    city: City.bangalore,
    stage: LeadStage.enquiryReceived,
    area: 'Whitefield',
    plotSize: '30x40',
    budget: '45-50 Lakhs',
    assignedTo: 'tc_1',
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    notes: 'Interested in full construction. Has 30x40 plot in Whitefield.',
    callLogs: [],
  ),
  Lead(
    id: '2',
    name: 'Priya Sharma',
    phone: '8765432109',
    source: LeadSource.instagram,
    serviceType: ServiceType.interiors,
    city: City.bangalore,
    stage: LeadStage.telecallerCallDone,
    area: 'Koramangala',
    budget: '15-20 Lakhs',
    assignedTo: 'tc_1',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    lastContactedAt: DateTime.now().subtract(const Duration(hours: 5)),
    followupAt: DateTime.now().add(const Duration(days: 2)),
    lastOutcome: CallOutcome.interested,
    callLogs: [
      CallLog(id: 'cl_1', calledAt: DateTime.now().subtract(const Duration(hours: 5)), durationSeconds: 540, outcome: CallOutcome.interested, notes: 'Wants 2BHK interiors.'),
    ],
  ),
  Lead(
    id: '3',
    name: 'Suresh Nair Kiran',
    phone: '7654321098',
    source: LeadSource.website,
    serviceType: ServiceType.renovation,
    city: City.mysore,
    stage: LeadStage.meetingAtOffice,
    area: 'Vijayanagar',
    plotSize: '20x30',
    budget: '8-12 Lakhs',
    assignedTo: 'tc_1',
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
    lastContactedAt: DateTime.now().subtract(const Duration(days: 1)),
    followupAt: DateTime.now().subtract(const Duration(hours: 3)),
    lastOutcome: CallOutcome.callback,
    callLogs: [
      CallLog(id: 'cl_2', calledAt: DateTime.now().subtract(const Duration(days: 2)), durationSeconds: 720, outcome: CallOutcome.interested),
      CallLog(id: 'cl_3', calledAt: DateTime.now().subtract(const Duration(days: 1)), durationSeconds: 380, outcome: CallOutcome.callback),
    ],
  ),

  // tc_2 — Sneha Rao
  Lead(
    id: '4',
    name: 'Anitha Reddy',
    phone: '6543210987',
    source: LeadSource.referral,
    serviceType: ServiceType.construction,
    city: City.bangalore,
    stage: LeadStage.quotationSent,
    area: 'Electronic City',
    plotSize: '40x60',
    budget: '60-70 Lakhs',
    assignedTo: 'tc_2',
    createdAt: DateTime.now().subtract(const Duration(days: 7)),
    lastContactedAt: DateTime.now().subtract(const Duration(days: 4)),
    followupAt: DateTime.now().subtract(const Duration(days: 1)),
    lastOutcome: CallOutcome.interested,
    notes: 'Referred by existing client Mohan Rao.',
    callLogs: [
      CallLog(id: 'cl_4', calledAt: DateTime.now().subtract(const Duration(days: 6)), durationSeconds: 900, outcome: CallOutcome.interested),
      CallLog(id: 'cl_5', calledAt: DateTime.now().subtract(const Duration(days: 4)), durationSeconds: 620, outcome: CallOutcome.interested),
      CallLog(id: 'cl_6', calledAt: DateTime.now().subtract(const Duration(hours: 4)), durationSeconds: 480, outcome: CallOutcome.callback),
    ],
  ),
  Lead(
    id: '5',
    name: 'Deepak Verma',
    phone: '9988776600',
    source: LeadSource.facebook,
    serviceType: ServiceType.construction,
    city: City.bangalore,
    stage: LeadStage.finalAgreement,
    area: 'JP Nagar',
    plotSize: '30x50',
    budget: '55-60 Lakhs',
    assignedTo: 'tc_2',
    createdAt: DateTime.now().subtract(const Duration(days: 20)),
    lastContactedAt: DateTime.now().subtract(const Duration(days: 2)),
    lastOutcome: CallOutcome.interested,
    callLogs: [
      CallLog(id: 'cl_7', calledAt: DateTime.now().subtract(const Duration(days: 18)), durationSeconds: 750, outcome: CallOutcome.interested),
      CallLog(id: 'cl_8', calledAt: DateTime.now().subtract(const Duration(days: 10)), durationSeconds: 960, outcome: CallOutcome.interested),
    ],
  ),

  // tc_3 — Arun Shetty
  Lead(
    id: '6',
    name: 'Mohammed Farhan',
    phone: '9988776655',
    source: LeadSource.phone,
    serviceType: ServiceType.interiors,
    city: City.mysore,
    stage: LeadStage.future,
    area: 'Mysore Road',
    budget: '20-25 Lakhs',
    assignedTo: 'tc_3',
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
    lastContactedAt: DateTime.now().subtract(const Duration(days: 5)),
    followupAt: DateTime.now().add(const Duration(days: 83)),
    lastOutcome: CallOutcome.future,
    futureTag: FutureTag.warm,
    notes: 'Planning interiors after house possession in 3 months.',
    callLogs: [
      CallLog(id: 'cl_9', calledAt: DateTime.now().subtract(const Duration(days: 5)), durationSeconds: 480, outcome: CallOutcome.future),
    ],
  ),
  Lead(
    id: '7',
    name: 'Kavitha Menon',
    phone: '8877665544',
    source: LeadSource.whatsapp,
    serviceType: ServiceType.construction,
    city: City.bangalore,
    stage: LeadStage.negotiation,
    area: 'Sarjapur Road',
    plotSize: '30x50',
    budget: '55-65 Lakhs',
    assignedTo: 'tc_3',
    createdAt: DateTime.now().subtract(const Duration(days: 12)),
    lastContactedAt: DateTime.now().subtract(const Duration(hours: 8)),
    followupAt: DateTime.now().add(const Duration(days: 1)),
    lastOutcome: CallOutcome.interested,
    notes: 'Price negotiation ongoing.',
    callLogs: [
      CallLog(id: 'cl_10', calledAt: DateTime.now().subtract(const Duration(days: 10)), durationSeconds: 840, outcome: CallOutcome.interested),
      CallLog(id: 'cl_11', calledAt: DateTime.now().subtract(const Duration(hours: 8)), durationSeconds: 300, outcome: CallOutcome.interested),
    ],
  ),

  // tc_4 — Divya Nair
  Lead(
    id: '8',
    name: 'Srinivas Murthy',
    phone: '9876501234',
    source: LeadSource.instagram,
    serviceType: ServiceType.interiors,
    city: City.bangalore,
    stage: LeadStage.siteVisit,
    area: 'Indiranagar',
    budget: '25-30 Lakhs',
    assignedTo: 'tc_4',
    createdAt: DateTime.now().subtract(const Duration(days: 4)),
    lastContactedAt: DateTime.now().subtract(const Duration(days: 1)),
    followupAt: DateTime.now().add(const Duration(days: 3)),
    lastOutcome: CallOutcome.interested,
    callLogs: [
      CallLog(id: 'cl_12', calledAt: DateTime.now().subtract(const Duration(days: 3)), durationSeconds: 660, outcome: CallOutcome.interested),
      CallLog(id: 'cl_13', calledAt: DateTime.now().subtract(const Duration(days: 1)), durationSeconds: 420, outcome: CallOutcome.interested),
    ],
  ),
  Lead(
    id: '9',
    name: 'Lakshmi Prasad',
    phone: '8765109876',
    source: LeadSource.website,
    serviceType: ServiceType.renovation,
    city: City.bangalore,
    stage: LeadStage.telecallerCallDone,
    area: 'Banashankari',
    budget: '10-15 Lakhs',
    assignedTo: 'tc_4',
    createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    lastContactedAt: DateTime.now().subtract(const Duration(hours: 1)),
    followupAt: DateTime.now().add(const Duration(days: 1)),
    lastOutcome: CallOutcome.callback,
    callLogs: [
      CallLog(id: 'cl_14', calledAt: DateTime.now().subtract(const Duration(hours: 1)), durationSeconds: 18, outcome: CallOutcome.notReachable),
      CallLog(id: 'cl_15', calledAt: DateTime.now().subtract(const Duration(minutes: 30)), durationSeconds: 390, outcome: CallOutcome.callback),
    ],
  ),

  // tc_5 — Kiran Hegde
  Lead(
    id: '10',
    name: 'Pooja Kulkarni',
    phone: '7654098765',
    source: LeadSource.facebook,
    serviceType: ServiceType.construction,
    city: City.mysore,
    stage: LeadStage.enquiryReceived,
    area: 'Vijayanagar',
    plotSize: '40x40',
    budget: '40-50 Lakhs',
    assignedTo: 'tc_5',
    createdAt: DateTime.now().subtract(const Duration(hours: 1)),
    callLogs: [],
  ),
  Lead(
    id: '11',
    name: 'Ganesh Rao',
    phone: '6543198765',
    source: LeadSource.referral,
    serviceType: ServiceType.construction,
    city: City.mysore,
    stage: LeadStage.enquiryReceived,
    area: 'Kuvempunagar',
    plotSize: '30x40',
    budget: '35-45 Lakhs',
    assignedTo: 'tc_5',
    createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    callLogs: [],
  ),

  // Future pipeline leads (mixed telecallers)
  Lead(
    id: '12',
    name: 'Arjun Shetty',
    phone: '9123456780',
    source: LeadSource.instagram,
    serviceType: ServiceType.construction,
    city: City.bangalore,
    stage: LeadStage.future,
    area: 'Hebbal',
    plotSize: '40x60',
    budget: '70-80 Lakhs',
    assignedTo: 'tc_1',
    createdAt: DateTime.now().subtract(const Duration(days: 15)),
    lastContactedAt: DateTime.now().subtract(const Duration(days: 14)),
    followupAt: DateTime.now().add(const Duration(days: 14)),
    lastOutcome: CallOutcome.future,
    futureTag: FutureTag.hot,
    notes: 'Son is working abroad, coming back in a month. Serious buyer.',
    callLogs: [
      CallLog(id: 'cl_16', calledAt: DateTime.now().subtract(const Duration(days: 14)), durationSeconds: 720, outcome: CallOutcome.future),
    ],
  ),
  Lead(
    id: '13',
    name: 'Nalini Krishnaswamy',
    phone: '8234567891',
    source: LeadSource.referral,
    serviceType: ServiceType.interiors,
    city: City.bangalore,
    stage: LeadStage.future,
    area: 'Bannerghatta Road',
    budget: '18-22 Lakhs',
    assignedTo: 'tc_2',
    createdAt: DateTime.now().subtract(const Duration(days: 20)),
    lastContactedAt: DateTime.now().subtract(const Duration(days: 18)),
    followupAt: DateTime.now().add(const Duration(days: 45)),
    lastOutcome: CallOutcome.future,
    futureTag: FutureTag.warm,
    notes: 'Flat handover in 6 weeks. Wants premium interiors package.',
    callLogs: [
      CallLog(id: 'cl_17', calledAt: DateTime.now().subtract(const Duration(days: 18)), durationSeconds: 540, outcome: CallOutcome.future),
    ],
  ),
  Lead(
    id: '14',
    name: 'Vivek Acharya',
    phone: '7345678902',
    source: LeadSource.facebook,
    serviceType: ServiceType.construction,
    city: City.mysore,
    stage: LeadStage.future,
    area: 'Kuvempunagar',
    plotSize: '30x40',
    budget: '38-45 Lakhs',
    assignedTo: 'tc_3',
    createdAt: DateTime.now().subtract(const Duration(days: 30)),
    lastContactedAt: DateTime.now().subtract(const Duration(days: 28)),
    followupAt: DateTime.now().add(const Duration(days: 90)),
    lastOutcome: CallOutcome.future,
    futureTag: FutureTag.cool,
    notes: 'Land dispute being resolved. Will start construction after 3 months.',
    callLogs: [
      CallLog(id: 'cl_18', calledAt: DateTime.now().subtract(const Duration(days: 28)), durationSeconds: 360, outcome: CallOutcome.future),
    ],
  ),
  Lead(
    id: '15',
    name: 'Rekha Subramaniam',
    phone: '6456789013',
    source: LeadSource.website,
    serviceType: ServiceType.renovation,
    city: City.bangalore,
    stage: LeadStage.future,
    area: 'Jayanagar',
    budget: '12-16 Lakhs',
    assignedTo: 'tc_4',
    createdAt: DateTime.now().subtract(const Duration(days: 45)),
    lastContactedAt: DateTime.now().subtract(const Duration(days: 44)),
    followupAt: DateTime.now().add(const Duration(days: 210)),
    lastOutcome: CallOutcome.future,
    futureTag: FutureTag.longTerm,
    notes: 'Children\'s school year ends in June. Will renovate after summer.',
    callLogs: [
      CallLog(id: 'cl_19', calledAt: DateTime.now().subtract(const Duration(days: 44)), durationSeconds: 420, outcome: CallOutcome.future),
    ],
  ),
];
